### ISSUE TITLE
Problem with pip during installation

### ISSUE THREAD

**Issue by elmohaya** [mit-acl/gym-collision-avoidance#12]
Hello,

I am a student at the University of Michigan and currently conducting research in the area of multi-agent collision avoidance. I am trying to install the package through Anaconda however I receive the following error:

>> pip install gym_collision_avoidance

ERROR: Could not find a version that satisfies the requirement gym_collision_avoidance (from versions: none)
ERROR: No matching distribution found for gym_collision_avoidance

Thank you!

**Comment by mfe7** [comment]
There is a (possibly outdated) [package](https://pypi.org/project/gym-collision-avoidance/) available through pypi, but I wonder if it requires an older version of python than what you have? I doubt that python constraint is super important to get the code to run, but I set it that way a while back when trying to get dependencies working. You might instead want to try installing "from source" by following along the docs in this repo.

**Comment by elmohaya** [comment]
Thank you. I tried to use the From Source code on the Ubuntu subsystem on Windows 10 with python 3.8 and received the following error:

ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.14 (from gym-collision-avoidance) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow<2.0,>=1.14

Appreciate your time and help. Thanks.

**Comment by mfe7** [comment]
Ah, I see. That explains why we had the python < 3.8 requirement -- some of the code was written a while ago (before tensorflow 2) and it seems like newer python versions don't have an associated tensorflow 1 package available. It probably isn't that hard to modify the code so that it supports tensorflow 2 (I think for other projects I've replaced `import tensorflow as tf` with `import tensorflow.compat.v1 as tf` as a workaround, but may require going through several files. I can try to find time for this in the next couple weeks, or if you are interested, I would gladly accept a pull request with this change!

**Comment by mfe7** [comment]
this issue was hopefully addressed by the patch provided in #14 which now allows using more modern python versions and tf2, will get that commit pushed into this public repo shortly

**Comment by mfe7** [comment]
should be fixed now
